#!/bin/bash

if [ -z "$1" ]; then
    echo './run [dev|test]'
    exit
fi

if [ $1 == 'dev' ]; then
    export NODE_ENV=develop
    export NODE_WATCH=true
    npm run dev
elif [ $1 == 'test' ]; then
    export NODE_ENV=test
    export NODE_WATCH=true
    npm test
fi